/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : XLS
 #	author : miyako
 #	2015/01/21
 #
 # --------------------------------------------------------------------------------*/



// --- Workbook
void XLS_WORKBOOK_Create_format(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_Create_font(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_Save_document(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_CLEAR(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_Create(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_Create_sheet(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_Create_fn0_node(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_Create_area_node(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_Create_cell_node(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_Create_fn1_node(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKBOOK_Create_fn2_node(sLONG_PTR *pResult, PackagePtr pParams);

// --- Worksheet
void XLS_WORKSHEET_Set_cell_real(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_Set_cell_text(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_SET_ROW_HEIGHT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_SET_COL_WIDTH(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_MERGE_CELLS(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_Get_cell_range(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_Get_cell(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_Set_cell_bool(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_Set_cell_note(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_Set_cell_link(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_Set_cell_fn(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_WORKSHEET_RELEASE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Cell
void XLS_CELL_SET_FONT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_FORMAT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_Get_row(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_Get_col(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_NUMERIC_FORMAT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_Get_format(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_ITALIC(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_STRIKEOUT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_SHADOW(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_SCRIPT_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_UNDERLINE_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_BOLDNESS(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_FONT_HEIGHT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_FONT_NAME(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_HIDDEN(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_LOCKED(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_BORDER_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_WRAP(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_HALIGN(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_VALIGN(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_ORIENTATION(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_COLOR(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_FILL_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_SET_BORDER_COLOR(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_CELL_RELEASE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Range
void XLS_RANGE_SET_FONT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_NUMERIC_FORMAT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_ITALIC(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_STRIKEOUT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_SHADOW(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_SCRIPT_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_UNDERLINE_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_BOLDNESS(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_FONT_HEIGHT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_FONT_NAME(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_HIDDEN(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_LOCKED(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_BORDER_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_WRAP(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_HALIGN(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_VALIGN(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_ORIENTATION(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_COLOR(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_FILL_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_SET_BORDER_COLOR(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_RANGE_RELEASE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Font
void XLS_FONT_SET_NAME(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_SET_HEIGHT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_SET_BOLDNESS(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_SET_UNDERLINE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_SET_SCRIPT_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_SET_COLOR(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_SET_STRIKEOUT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_SET_SHADOW(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_Get_name(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_Get_height(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_Get_boldness(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_Get_underline(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_Get_script_style(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_Get_color_id(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_Get_strikeout(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_Get_shadow(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_SET_ITALIC(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_Get_italic(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FONT_RELEASE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Format
void XLS_FORMAT_Get_valign(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_FONT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_font(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_NUMERIC_FORMAT(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_numeric_format(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_HALIGN(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_VALIGN(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_ORIENTATION(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_COLOR(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_FILL_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_WRAP(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_BORDER_STYLE(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_LOCKED(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_HIDDEN(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_halign(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_orientation(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_GET_COLOR_ID(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_fill_style(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_wrap(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_SET_BORDER_COLOR(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_border_style(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_border_color_id(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_locked(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_Get_hidden(sLONG_PTR *pResult, PackagePtr pParams);
void XLS_FORMAT_RELEASE(sLONG_PTR *pResult, PackagePtr pParams);

// --- Node
void XLS_NODE_RELEASE(sLONG_PTR *pResult, PackagePtr pParams);
